touchscreen: gt1151q: Don't use clang's builtin defs for fwrite
We have it defined in the driver itself. Using clang's defs leads to errors like:

drivers/built-in.o: In function `_save_testing_data':
kernel/xiaomi/onclite/drivers/input/touchscreen/gt1151q/test_function.c:xxxx: undefined reference to `fwrite_unlocked'
kernel/xiaomi/onclite/drivers/input/touchscreen/gt1151q/test_function.c:xxxx: undefined reference to `fwrite_unlocked'
kernel/xiaomi/onclite/drivers/input/touchscreen/gt1151q/test_function.c:xxxx: undefined reference to `fwrite_unlocked'
kernel/xiaomi/onclite/drivers/input/touchscreen/gt1151q/test_function.c:xxxx: undefined reference to `fwrite_unlocked'
kernel/xiaomi/onclite/drivers/input/touchscreen/gt1151q/test_function.c:xxxx: undefined reference to `fwrite_unlocked'
drivers/built-in.o:kernel/xiaomi/onclite/drivers/input/touchscreen/gt1151q/test_function.c:1112: more undefined references to `fwrite_unlocked' follow

- Required after: llvm-mirror/clang@0504bf2

Change-Id: I61498d2f14afb194df723c3fea31aee4a572b6ed
Signed-off-by: theimpulson <aayushgupta219@gmail.com>
Signed-off-by: Dhina17 <dhinalogu@gmail.com>